[linux.plasma]
command = "dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript string:\"var allDesktops = desktops(); for (i = 0; i < allDesktops.length; i++) { d = allDesktops[i]; d.wallpaperPlugin = 'org.kde.image'; d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General'); d.writeConfig('Image', 'file://{IMG}'); }\""

[linux.gnome]
command = "gsettings set org.gnome.desktop.background picture-uri file://{IMG} && gsettings set org.gnome.desktop.background picture-uri-dark file://{IMG}"

[linux.gnome-wayland]
command = "gsettings set org.gnome.desktop.background picture-uri file://{IMG} && gsettings set org.gnome.desktop.background picture-uri-dark file://{IMG}"

[linux.ubuntu]
command = "gsettings set org.gnome.desktop.background picture-uri file://{IMG} && gsettings set org.gnome.desktop.background picture-uri-dark file://{IMG}"

[linux.cinnamon]
command = "gsettings set org.cinnamon.desktop.background picture-uri file://{IMG}"

[linux.mate]
command = "gsettings set org.mate.background picture-filename \"{IMG}\""

[linux.budgie-desktop]
command = "gsettings set org.gnome.desktop.background picture-uri \"file://{IMG}\""

[linux.xfce]
command = "for prop in $(xfconf-query -c xfce4-desktop -l | grep last-image); do xfconf-query -c xfce4-desktop -p $prop -s '{IMG}'; done"

[macos]
command = "osascript -e 'tell application \"System Events\" to set picture of every desktop to POSIX file \"{IMG}\"'"
