name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the app
        run: cargo build --release

      - name: Package the binary
        run: |
          mkdir -p dist
          cp target/release/wallheaven dist/
          cd dist
          tar -czvf wallheaven-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz wallheaven

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: wallheaven-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          path: dist/wallheaven-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wallheaven-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wallheaven-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
